---
configure_dotfiles: false
configure_terminal: true
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - TV
 - Podcasts
dockitems_persist:
  - name: "Terminal"
    path: "/Applications/Utilities/Terminal.app/"
    pos: 2
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app/"
    pos: 3
  - name: "Microsoft Outlook"
    path: "/Applications/Microsoft Outlook.app/"
    pos: 4
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 5
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 6
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 7
  - name: "Beyond Compare"
    path: "/Applications/Beyond Compare.app/"
    pos: 8

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - iperf
  - libevent
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - docker
  - azure-cli
  - opentofu
  - terraform
  - certbot

homebrew_taps:
 - hashicorp/tap

##  https://formulae.brew.sh/cask/
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - displaylink
  - google-chrome
  - brave-browser
  - firefox
  - jetbrains-toolbox
  - visual-studio-code
  - openvpn-connect
  - microsoft-azure-storage-explorer
  - beyond-compare
  - vlc
  - zoom
## TODO:  setup .net maui
## TODO:  setup parallels or somesuch, virtualbox does not have amd64 emulation
## TODO:  add option for Brian to have his mouse driver added
#  - logi-options+
#brew install --cask logi-options+

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
#  - {id: 497799835, name: "Xcode"}
mas_email: ""
#mas_email: bkhoyi@liquidx.com
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

## TODO:  add automation to install displaylink driver, office365, wifi credentials,